name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Android Build & Test
    runs-on: macOS-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Test
      run: ./gradlew test --stacktrace
#      run: ./gradlew testDebugUnitTest
    - name: Build with Gradle
      run: ./gradlew build
